# -*- mode: ruby -*-
# vi: set ft=ruby :

cpus   = ENV['RABBITMQ_SANDBOX_VM_CPUS']   || 2
memory = ENV['RABBITMQ_SANDBOX_VM_MEMORY'] || 2048

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure('2') do |config|
  config.vm.box = "almalinux/8"
  config.vm.box_version = "8.7.20230228"
  config.ssh.insert_key = false

  config.vm.provider 'libvirt' do |provider|
    provider.driver = 'kvm'
    provider.memory = memory
    provider.cpus = cpus
  end

  (1..3).each do |i|
    config.vm.define "rabbitmq-server#{i}" do |n|
      n.vm.hostname = "rabbitmq-server#{i}"
      n.vm.network 'private_network', ip: "192.168.57.20#{i}"
      n.vm.synced_folder '.', '/vagrant', create: true, owner: "vagrant", group: "vagrant", type: "sshfs"
      n.vm.provision :shell, inline: 'rsync -rtlv /vagrant/cache/dnf /var/cache/ || true'
      n.vm.provision :shell, path:   'scripts/setup.sh'
      n.vm.provision :shell, inline: 'rsync -rtlv /var/cache/dnf /vagrant/cache/'
    end
  end

  config.vm.define "rabbitmq-client" do |n|
    n.vm.hostname = "rabbitmq-client"
    n.vm.network 'private_network', ip: "192.168.57.101"
    n.vm.synced_folder '.', '/vagrant', create: true, owner: "vagrant", group: "vagrant", type: "sshfs"
  end
end
