# -*- mode: ruby -*-
# vi: set ft=ruby :

cpus   = ENV['RABBITMQ_SANDBOX_VM_CPUS']   || 2
memory = ENV['RABBITMQ_SANDBOX_VM_MEMORY'] || 2048

ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'libvirt'

third_octet = if ENV['VAGRANT_DEFAULT_PROVIDER'] == "libvirt" then 57
              elsif ENV['VAGRANT_DEFAULT_PROVIDER'] == "virtualbox" then 56
              else abort "VAGRANT_DEFAULT_PROVIDER required 'libvirt' or 'virtualbox'" end

Vagrant.configure('2') do |config|
  config.vm.box = "almalinux/8"
  config.vm.box_version = "8.7.20230228"
  config.ssh.insert_key = false

  config.vm.provider 'libvirt' do |provider|
    provider.driver = 'kvm'
    provider.memory = memory
    provider.cpus = cpus
  end

  config.vm.provider 'virtualbox' do |provider|
    provider.memory = memory
    provider.cpus = cpus
  end

  (1..3).each do |i|
    config.vm.define "rabbitmq-server#{i}" do |n|
      n.vm.hostname = "rabbitmq-server#{i}"
      n.vm.network 'private_network', ip: "192.168.#{third_octet}.20#{i}"
      n.vm.synced_folder '.', '/vagrant', create: true, owner: "vagrant", group: "vagrant", type: "sshfs"
      n.vm.provision :shell, inline: <<~EOS_VAGRANT
        cat << 'EOS' >> /etc/hosts
        192.168.#{third_octet}.201 rabbitmq-server1
        192.168.#{third_octet}.202 rabbitmq-server2
        192.168.#{third_octet}.203 rabbitmq-server3
        192.168.#{third_octet}.101 rabbitmq-client
        EOS
      EOS_VAGRANT
      n.vm.provision :shell, inline: 'dnf install -y rsync || true'
      n.vm.provision :shell, inline: 'rsync -rtlv /vagrant/cache/dnf /var/cache/ || true'
      n.vm.provision :shell, path:   'scripts/setup.sh'
      n.vm.provision :shell, inline: 'rsync -rtlv /var/cache/dnf /vagrant/cache/'
    end
  end

  config.vm.define "rabbitmq-client" do |n|
    n.vm.hostname = "rabbitmq-client"
    n.vm.network 'private_network', ip: "192.168.#{third_octet}.101"
    n.vm.synced_folder '.', '/vagrant', create: true, owner: "vagrant", group: "vagrant", type: "sshfs"
    n.vm.provision :shell, inline: <<~EOS_VAGRANT
      cat << 'EOS' >> /etc/hosts
      192.168.#{third_octet}.201 rabbitmq-server1
      192.168.#{third_octet}.202 rabbitmq-server2
      192.168.#{third_octet}.203 rabbitmq-server3
      192.168.#{third_octet}.101 rabbitmq-client
      EOS
    EOS_VAGRANT
  end
end
